from .weightedBinaryCrossEntropy import WeightedBinaryCrossEntropy, W_BCEWithLogitsLoss
from .contrastiveLoss import contrastive_loss, compute_contrastive_loss
from .triple_loss import compute_triplet_loss